from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from pythonbasicio.test.mainone.config.ConfigStore import *
from pythonbasicio.test.mainone.udfs.UDFs import *

def Script_5(spark: SparkSession, in0: DataFrame) -> DataFrame:

    def test_random_script():
        spark.sql("USE CATALOG apollo11")
        isInputEmpty = input102.rdd.isEmpty()

        if isInputEmpty:
            columns = [lit(None).cast(f.dataType).alias(f.name) for f in input102.schema.fields]
            input102 = spark.createDataFrame([Row()]).select(columns)

        output101 = None
        input102 = input102.withColumn(
            "_sql_query",
            array(
              lit("""truncate table bz_marketing_data.mktg_stg_master_lead_contact;"""),
              lit(
                """INSERT INTO bz_marketing_data.mktg_stg_master_lead_contact
    (
      Lead_Contact_ID,
      Contact_id,
      Lead_id,
      Account_id,
      Name,
      Street,
      City,
      State,
      PostalCode,
      Country,
      State_Code,
      Country_Code,
      phone,
      mobilephone,
      email,
      Title,
      LeadSource,
      createddate,
      lastmodifieddate,
      lastactivitydate,
      no_longer_w_company__c,
      functional_role__c,
      job_level__c,
      marketingcloudid__c,
      engagement_status__c,
      engagement_product__c,
      marketing_suspended__c,
      current_sequence_name__c,
      name_of_currently_active_sequence__c,
      marketo_person_id__c,
      isconverted,
      converteddate,
      valid_domain,
      last_qualified_campaign__c,
      Reject_Reason,
      LeadCreateddate,
      Email_Opt_In__c,
      Is_Exec_Sponsor_Contact__c,
      Is_Named_Supp__c,
      owner,
      CSD_Prospecting__c,
      HasOptedOutOfEmail,
      Last_MQL__c,
      isdeleted,
      Zoominfo_Contact_Source__c,
      etl_updated_date
    )
    SELECT Lead_Contact_ID,
           Contact_id,
           Lead_id,
           Account_id,
           Name,
           Street,
           City,
           State,
           PostalCode,
           Country,
           State_Code,
           Country_Code,
           phone,
           mobilephone,
           email,
           Title,
           LeadSource,
           createddate,
           lastmodifieddate,
           lastactivitydate,
           no_longer_w_company__c,
           functional_role__c,
           job_level__c,
           marketingcloudid__c,
           engagement_status__c,
           engagement_product__c,
           marketing_suspended__c,
           current_sequence_name__c,
           name_of_currently_active_sequence__c,
           marketo_person_id__c,
           isconverted,
           converteddate,
           valid_domain,
           last_qualified_campaign__c,
           Reject_Reason,
           LeadCreateddate,
           Email_Opt_In__c,
           Is_Exec_Sponsor_Contact__c,
           Is_Named_Supp__c,
           OWNER,
           CSD_Prospecting__c,
           HasOptedOutOfEmail,
           Last_MQL__c,
           isdeleted,
           Zoominfo_Contact_Source__c,
           CURRENT_TIMESTAMP
    FROM (SELECT Id AS Lead_Contact_ID,
                 Id AS Contact_id,
                 NULL AS Lead_id,
                 accountid AS Account_id,
                 name AS Name,
                 mailingstreet AS Street,
                 mailingcity AS City,
                 mailingstate AS State,
                 mailingpostalcode AS PostalCode,
                 mailingcountry AS Country,
                 mailingstatecode AS State_Code,
                 mailingcountrycode AS Country_Code,
                 phone AS phone,
                 mobilephone AS mobilephone,
                 email AS email,
                 title AS Title,
                 leadsource AS LeadSource,
                 createddate AS createddate,
                 lastmodifieddate AS lastmodifieddate,
                 lastactivitydate AS lastactivitydate,
                 no_longer_w_company__c AS no_longer_w_company__c,
                 functional_role__c AS functional_role__c,
                 job_level__c AS job_level__c,
                 marketingcloudid__c AS marketingcloudid__c,
                 engagement_status__c AS engagement_status__c,
                 engagement_product__c AS engagement_product__c,
                 marketing_suspended__c AS marketing_suspended__c,
                 current_sequence_name__c AS current_sequence_name__c,
                 name_of_currently_active_sequence__c AS name_of_currently_active_sequence__c,
                 marketo_person_id__c AS marketo_person_id__c,
                 NULL AS isconverted,
                 NULL AS converteddate,
                 email_in_valid_domain__c AS valid_domain,
                 last_qualified_campaign__c AS last_qualified_campaign__c,
                 Reject_Recycle_Reason__c AS Reject_Reason,
                 NULL AS LeadCreateddate,
                 Email_Opt_In__c,
                 Is_Exec_Sponsor_Contact__c,
                 Is_Named_Supp__c,
                 ownerid AS OWNER,
                 CSD_Prospecting__c,
                 HasOptedOutOfEmail,
                 Last_MQL__c,
                 isdeleted,
                 Zoominfo_Contact_Source__c
          FROM (SELECT dl_sfdc_contact.id,
                       dl_sfdc_contact.isdeleted,
                       dl_sfdc_contact.masterrecordid,
                       dl_sfdc_contact.accountid,
                       dl_sfdc_contact.lastname,
                       dl_sfdc_contact.firstname,
                       dl_sfdc_contact.salutation,
                       dl_sfdc_contact.name,
                       dl_sfdc_contact.recordtypeid,
                       dl_sfdc_contact.otherstreet,
                       dl_sfdc_contact.othercity,
                       dl_sfdc_contact.otherstate,
                       dl_sfdc_contact.otherpostalcode,
                       dl_sfdc_contact.othercountry,
                       dl_sfdc_contact.otherstatecode,
                       dl_sfdc_contact.othercountrycode,
                       dl_sfdc_contact.othergeocodeaccuracy,
                       dl_sfdc_contact.mailingstreet,
                       dl_sfdc_contact.mailingcity,
                       dl_sfdc_contact.mailingstate,
                       dl_sfdc_contact.mailingpostalcode,
                       dl_sfdc_contact.mailingcountry,
                       dl_sfdc_contact.mailingstatecode,
                       dl_sfdc_contact.mailingcountrycode,
                       dl_sfdc_contact.mailinggeocodeaccuracy,
                       dl_sfdc_contact.phone,
                       dl_sfdc_contact.fax,
                       dl_sfdc_contact.mobilephone,
                       dl_sfdc_contact.homephone,
                       dl_sfdc_contact.otherphone,
                       dl_sfdc_contact.assistantphone,
                       dl_sfdc_contact.reportstoid,
                       dl_sfdc_contact.email,
                       dl_sfdc_contact.title,
                       dl_sfdc_contact.department,
                       dl_sfdc_contact.assistantname,
                       dl_sfdc_contact.leadsource,
                       dl_sfdc_contact.birthdate,
                       dl_sfdc_contact.description,
                       dl_sfdc_contact.currencyisocode,
                       dl_sfdc_contact.ownerid,
                       dl_sfdc_contact.hasoptedoutofemail,
                       dl_sfdc_contact.hasoptedoutoffax,
                       dl_sfdc_contact.donotcall,
                       dl_sfdc_contact.canallowportalselfreg,
                       dl_sfdc_contact.createddate,
                       dl_sfdc_contact.createdbyid,
                       dl_sfdc_contact.lastmodifieddate,
                       dl_sfdc_contact.lastmodifiedbyid,
                       dl_sfdc_contact.systemmodstamp,
                       dl_sfdc_contact.lastactivitydate,
                       dl_sfdc_contact.lastcurequestdate,
                       dl_sfdc_contact.lastcuupdatedate,
                       dl_sfdc_contact.lastvieweddate,
                       dl_sfdc_contact.lastreferenceddate,
                       dl_sfdc_contact.emailbouncedreason,
                       dl_sfdc_contact.emailbounceddate,
                       dl_sfdc_contact.isemailbounced,
                       dl_sfdc_contact.photourl,
                       dl_sfdc_contact.jigsaw,
                       dl_sfdc_contact.jigsawcontactid,
                       dl_sfdc_contact.cleanstatus,
                       dl_sfdc_contact.alma_mater__c,
                       dl_sfdc_contact.preferred_communication__c,
                       dl_sfdc_contact.comments_handling_instructions__c,
                       dl_sfdc_contact.names_of_pets__c,
                       dl_sfdc_contact.former_employers__c,
                       dl_sfdc_contact.names_of_family__c,
                       dl_sfdc_contact.asst_email__c,
                       dl_sfdc_contact.newsletter__c,
                       dl_sfdc_contact.no_longer_w_company__c,
                       dl_sfdc_contact.hr_webinar_11_14_06__c,
                       dl_sfdc_contact.it_webinar_11_14_06__c,
                       dl_sfdc_contact.registered_through__c,
                       dl_sfdc_contact.contact_bio__c,
                       dl_sfdc_contact.primary_contact__c,
                       dl_sfdc_contact.name_of_referral__c,
                       dl_sfdc_contact.release_bulletin__c,
                       dl_sfdc_contact.functional_role__c,
                       dl_sfdc_contact.event_location__c,
                       dl_sfdc_contact.purge_or_archive__c,
                       dl_sfdc_contact.job_level__c,
                       dl_sfdc_contact.validation__c,
                       dl_sfdc_contact.validation_date__c,
                       dl_sfdc_contact.roi_analysis_link__c,
                       dl_sfdc_contact.engagement_stage_time_delay__c,
                       dl_sfdc_contact.sd_contactid__c,
                       dl_sfdc_contact.sd_contactchk__c,
                       dl_sfdc_contact.program_name__c,
                       dl_sfdc_contact.account_update__c,
                       dl_sfdc_contact.tempmailingcountry__c,
                       dl_sfdc_contact.tempmailingstate__c,
                       dl_sfdc_contact.tempothercountry__c,
                       dl_sfdc_contact.tempotherstate__c,
                       dl_sfdc_contact.consent_last_updated__c,
                       dl_sfdc_contact.token__c,
                       dl_sfdc_contact.events__c,
                       dl_sfdc_contact.legacy_rn_orgid__c,
                       dl_sfdc_contact.legacy_rn_contactid__c,
                       dl_sfdc_contact.support_notes__c,
                       dl_sfdc_contact.support_relationship__c,
                       dl_sfdc_contact.inactive__c,
                       dl_sfdc_contact.timezone__c,
                       dl_sfdc_contact.reference__c,
                       dl_sfdc_contact.reference_status__c,
                       dl_sfdc_contact.reference_rank__c,
                       dl_sfdc_contact.reference_talk_track__c,
                       dl_sfdc_contact.references_given__c,
                       dl_sfdc_contact.reference_feedback__c,
                       dl_sfdc_contact.account_status__c,
                       dl_sfdc_contact.account_type__c,
                       dl_sfdc_contact.named_support_contact__c,
                       dl_sfdc_contact.employee_range__c,
                       dl_sfdc_contact.upgrade_replace__c,
                       dl_sfdc_contact.fortune_1_000__c,
                       dl_sfdc_contact.ls_lead_rating__c,
                       dl_sfdc_contact.jsimpacts__data_com_does_not_auto_update__c,
                       dl_sfdc_contact.server_path__c,
                       dl_sfdc_contact.lead_rating_image__c,
                       dl_sfdc_contact.qualification_meter__c,
                       dl_sfdc_contact.interest_meter__c,
                       dl_sfdc_contact.profile_completeness_meter__c,
                       dl_sfdc_contact.profile_status__c,
                       dl_sfdc_contact.interest_score_changed__c,
                       dl_sfdc_contact.last_interest_score_change_date__c,
                       dl_sfdc_contact.unsync_with_mkto__c,
                       dl_sfdc_contact.tenant_administrator_email_date__c,
                       dl_sfdc_contact.contact_subcontracting_status__c,
                       dl_sfdc_contact.is_customer_account__c,
                       dl_sfdc_contact.qbdialer__closedate__c,
                       dl_sfdc_contact.qbdialer__contactdate__c,
                       dl_sfdc_contact.qbdialer__contactscoreid__c,
                       dl_sfdc_contact.marketingcloudid__c,
                       dl_sfdc_contact.integrate_publisher_id__c,
                       dl_sfdc_contact.secondary_training_coordinator__c,
                       dl_sfdc_contact.jira_username__c,
                       dl_sfdc_contact.lid__linkedin_company_id__c,
                       dl_sfdc_contact.lid__linkedin_member_token__c,
                       dl_sfdc_contact.case_team_member_opt_in__c,
                       dl_sfdc_contact.contact_prior_company_email__c,
                       dl_sfdc_contact.marketo_phone__c,
                       dl_sfdc_contact.certification_date_expired__c,
                       dl_sfdc_contact.demand_funnel_stage__c,
                       dl_sfdc_contact.partner_merger_indicator__c,
                       dl_sfdc_contact.email_in_valid_domain__c,
                       dl_sfdc_contact.named_support_contact_inactivation_date__c,
                       dl_sfdc_contact.do_not_notify_community__c,
                       dl_sfdc_contact.laptop_workday_certified__c,
                       dl_sfdc_contact.security_message__c,
                       dl_sfdc_contact.partner_region_map__c,
                       dl_sfdc_contact.primary_work_country__c,
                       dl_sfdc_contact.primary_work_state_province__c,
                       dl_sfdc_contact.address_comments_primary_country__c,
                       dl_sfdc_contact.converted_from_lead__c,
                       dl_sfdc_contact.certification_status_new__c,
                       dl_sfdc_contact.product_lead__c,
                       dl_sfdc_contact.contact_status__c,
                       dl_sfdc_contact.date_onboarded__c,
                       dl_sfdc_contact.exclude_from_reporting__c,
                       dl_sfdc_contact.partner_contact_role__c,
                       dl_sfdc_contact.partner_offering_map__c,
                       dl_sfdc_contact.product_function__c,
                       dl_sfdc_contact.partner_segment__c,
                       dl_sfdc_contact.rm_comments__c,
                       dl_sfdc_contact.offshore__c,
                       dl_sfdc_contact.certification_status__c,
                       dl_sfdc_contact.merge_status__c,
                       dl_sfdc_contact.consultant_type__c,
                       dl_sfdc_contact.primary_language__c,
                       dl_sfdc_contact.contact_intelligence_dashboard__c,
                       dl_sfdc_contact.partner_stage__c,
                       dl_sfdc_contact.extension__c,
                       dl_sfdc_contact.address_comments__c,
                       dl_sfdc_contact.lms_user_id__c,
                       dl_sfdc_contact.partner_onboarding_comments__c,
                       dl_sfdc_contact.prior_consultant_record__c,
                       dl_sfdc_contact.consultant_internal_validation_complete__c,
                       dl_sfdc_contact.consultant_internal_validation_required__c,
                       dl_sfdc_contact.contact_exist_in_workday_ecosystem_prior__c,
                       dl_sfdc_contact.partner_validation_requested_by__c,
                       dl_sfdc_contact.primary_main_contact__c,
                       dl_sfdc_contact.prior_company_name__c,
                       dl_sfdc_contact.prior_consultnat_lms_id__c,
                       dl_sfdc_contact.request_it_jira_request__c,
                       dl_sfdc_contact.full_name__c,
                       dl_sfdc_contact.survey_responses__c,
                       dl_sfdc_contact.hire_date__c,
                       dl_sfdc_contact.prior_partner_contact_role__c,
                       dl_sfdc_contact.keep_informed_about_workday__c,
                       dl_sfdc_contact.main_concerns_with_current_hr_system__c,
                       dl_sfdc_contact.plans_for_hr_system__c,
                       dl_sfdc_contact.plans_for_current_financial_system__c,
                       dl_sfdc_contact.plans_for_your_current_system__c,
                       dl_sfdc_contact.demand_base_id__c,
                       dl_sfdc_contact.certification_name_expired__c,
                       dl_sfdc_contact.workday_services_region__c,
                       dl_sfdc_contact.send_exp_notification__c,
                       dl_sfdc_contact.workday_market_place_coordinator__c,
                       dl_sfdc_contact.date_offboarded__c,
                       dl_sfdc_contact.leave_of_absence__c,
                       dl_sfdc_contact.transfered__c,
                       dl_sfdc_contact.certification_image__c,
                       dl_sfdc_contact.oldest_certification_year__c,
                       dl_sfdc_contact.contacts_user__c,
                       dl_sfdc_contact.privacy_policy_agreement__c,
                       dl_sfdc_contact.contact_not_eligible_for_subcontracting__c,
                       dl_sfdc_contact.training_coordinator__c,
                       dl_sfdc_contact.user__c,
                       dl_sfdc_contact.industry__c,
                       dl_sfdc_contact.rising_14__c,
                       dl_sfdc_contact.rising_14_job_level__c,
                       dl_sfdc_contact.rising_14_job_title__c,
                       dl_sfdc_contact.rising_14_what_workday_applications_s__c,
                       dl_sfdc_contact.rising_14_how_many_years_of_experience__c,
                       dl_sfdc_contact.custom_start__c,
                       dl_sfdc_contact.new_cert_status__c,
                       dl_sfdc_contact.oldest_cert_date__c,
                       dl_sfdc_contact.oldest_active_cert_date__c,
                       dl_sfdc_contact.workday_user__c,
                       dl_sfdc_contact.worker_type__c,
                       dl_sfdc_contact.expiration_notification__c,
                       dl_sfdc_contact.date_of_check__c,
                       dl_sfdc_contact.encryption_check_performed__c,
                       dl_sfdc_contact.results_of_check__c,
                       dl_sfdc_contact.comments_laptopencryption__c,
                       dl_sfdc_contact.location_worker_type_interim__c,
                       dl_sfdc_contact.account_name__c,
                       dl_sfdc_contact.lef_access__c,
                       dl_sfdc_contact.lef_certified_contact__c,
                       dl_sfdc_contact.lef_enabled__c,
                       dl_sfdc_contact.lms_sync__c,
                       dl_sfdc_contact.lms_divison_status__c,
                       dl_sfdc_contact.marketo_job_title__c,
                       dl_sfdc_contact.ps_region__c,
                       dl_sfdc_contact.date_onboarded_depricated__c,
                       dl_sfdc_contact.user_department__c,
                       dl_sfdc_contact.engagement_status__c,
                       dl_sfdc_contact.send_email__c,
                       dl_sfdc_contact.qbdialer__lastcalltime__c,
                       dl_sfdc_contact.tenant_administrator__c,
                       dl_sfdc_contact.expired_wd24__c,
                       dl_sfdc_contact.partner_user__c,
                       dl_sfdc_contact.partner_user_access__c,
                       dl_sfdc_contact.consultant_internal_external_transfer__c,
                       dl_sfdc_contact.qbdialer__timezonesidkey__c,
                       dl_sfdc_contact.department_local_language__c,
                       dl_sfdc_contact.ae_connect_skuid__c,
                       dl_sfdc_contact.ae_connect__c,
                       dl_sfdc_contact.csd_comments__c,
                       dl_sfdc_contact.reject_sub_reason__c,
                       dl_sfdc_contact.disposition_detail__c,
                       dl_sfdc_contact.first_csd_ae_connect__c,
                       dl_sfdc_contact.first_csd_connect__c,
                       dl_sfdc_contact.first_csd_reachout__c,
                       dl_sfdc_contact.first_mql__c,
                       dl_sfdc_contact.first_marketing_response__c,
                       dl_sfdc_contact.first_sales_ae_connect__c,
                       dl_sfdc_contact.first_sales_connect__c,
                       dl_sfdc_contact.first_sales_reach_out__c,
                       dl_sfdc_contact.last_csd_ae_connect__c,
                       dl_sfdc_contact.last_csd_connect__c,
                       dl_sfdc_contact.last_csd_reachout__c,
                       dl_sfdc_contact.last_mql__c,
                       dl_sfdc_contact.last_marketing_response__c,
                       dl_sfdc_contact.last_sales_ae_connect__c,
                       dl_sfdc_contact.last_sales_connect__c,
                       dl_sfdc_contact.last_sales_reach_out__c,
                       dl_sfdc_contact.next_follow_up_date__c,
                       dl_sfdc_contact.next_step__c,
                       dl_sfdc_contact.how_long_in_current_role__c,
                       dl_sfdc_contact.last_email_csd__c,
                       dl_sfdc_contact.reject_recycle_reason__c,
                       dl_sfdc_contact.certified_consultant_workday_years_exp__c,
                       dl_sfdc_contact.marketing_opt_out__c,
                       dl_sfdc_contact.is_same_company_transfer__c,
                       dl_sfdc_contact.mkto_si__add_to_marketo_campaign__c,
                       dl_sfdc_contact.mkto_si__hidedate__c,
                       dl_sfdc_contact.mkto_si__last_interesting_moment_date__c,
                       dl_sfdc_contact.mkto_si__last_interesting_moment_desc__c,
                       dl_sfdc_contact.mkto_si__last_interesting_moment_source__c,
                       dl_sfdc_contact.mkto_si__last_interesting_moment_type__c,
                       dl_sfdc_contact.mkto_si__last_interesting_moment__c,
                       dl_sfdc_contact.mkto_si__relative_score__c,
                       dl_sfdc_contact.mkto_si__sales_insight__c,
                       dl_sfdc_contact.mkto_si__urgency__c,
                       dl_sfdc_contact.mkto_si__view_in_marketo__c,
                       dl_sfdc_contact.financials_logistics_systems_of_record2__c,
                       dl_sfdc_contact.hcm_systems_of_record__c,
                       dl_sfdc_contact.annual_revenue_range__c,
                       dl_sfdc_contact.contact_request__c,
                       dl_sfdc_contact.name_local_language__c,
                       dl_sfdc_contact.title_local_language__c,
                       dl_sfdc_contact.address_local_language__c,
                       dl_sfdc_contact.account_name_local_language__c,
                       dl_sfdc_contact.contact_id_case_safe__c,
                       dl_sfdc_contact.engagement_status_priority__c,
                       dl_sfdc_contact.marketing_notes__c,
                       dl_sfdc_contact.last_email_sales__c,
                       dl_sfdc_contact.most_recent_prequalified__c,
                       dl_sfdc_contact.fix__c,
                       dl_sfdc_contact.reject_reason_detail__c,
                       dl_sfdc_contact.most_recent_qualified_opportunity__c,
                       dl_sfdc_contact.adoption_kit_access__c,
                       dl_sfdc_contact.lms_access__c,
                       dl_sfdc_contact.support_role_integrations__c,
                       dl_sfdc_contact.training_coordinator_name__c,
                       dl_sfdc_contact.training_manager_lms_id__c,
                       dl_sfdc_contact.workday_role__c,
                       dl_sfdc_contact.contact_record_type__c,
                       dl_sfdc_contact.newsletters_blogs__c,
                       dl_sfdc_contact.isdupedelete__c,
                       dl_sfdc_contact.isdupeupdate__c,
                       dl_sfdc_contact.processed__c,
                       dl_sfdc_contact.istempdupe1__c,
                       dl_sfdc_contact.is_fax_blank__c,
                       dl_sfdc_contact.is_mobile_blank__c,
                       dl_sfdc_contact.is_name_blank__c,
                       dl_sfdc_contact.is_other_address_blank__c,
                       dl_sfdc_contact.is_other_phone_blank__c,
                       dl_sfdc_contact.is_email_blank__c,
                       dl_sfdc_contact.product_information_announcements__c,
                       dl_sfdc_contact.start_date_of_current_engagement_stage__c,
                       dl_sfdc_contact.key_contact__c,
                       dl_sfdc_contact.last_csd_reachout_task__c,
                       dl_sfdc_contact.sla_status__c,
                       dl_sfdc_contact.engagement_stage_end_date__c,
                       dl_sfdc_contact.prior_engagement_stage__c,
                       dl_sfdc_contact.engagement_type__c,
                       dl_sfdc_contact.consent_type__c,
                       dl_sfdc_contact.consent_source__c,
                       dl_sfdc_contact.etl_created_date,
                       dl_sfdc_contact.etl_created_by,
                       dl_sfdc_contact.etl_updated_date,
                       dl_sfdc_contact.etl_updated_by,
                       dl_sfdc_contact.certification_count__c,
                       dl_sfdc_contact.certification_status_code__c,
                       dl_sfdc_contact.contact_count__c,
                       dl_sfdc_contact.customer_contact_number__c,
                       dl_sfdc_contact.days_in_engagement_stage__c,
                       dl_sfdc_contact.engagement_stage_days_remaining__c,
                       dl_sfdc_contact.int_score__c,
                       dl_sfdc_contact.is_exec_sponsor_contact__c,
                       dl_sfdc_contact.is_named_supp__c,
                       dl_sfdc_contact.jsimpacts__data_com_managed__c,
                       dl_sfdc_contact.jsimpacts__imported_from_jigsaw__c,
                       dl_sfdc_contact.ls_completion__c,
                       dl_sfdc_contact.mailinglatitude,
                       dl_sfdc_contact.mailinglongitude,
                       dl_sfdc_contact.marketing_response_count__c,
                       dl_sfdc_contact.mkto_si__priority__c,
                       dl_sfdc_contact.mkto_si__relative_score_value__c,
                       dl_sfdc_contact.mkto_si__urgency_value__c,
                       dl_sfdc_contact.of_certifications__c,
                       dl_sfdc_contact.otherlatitude,
                       dl_sfdc_contact.otherlongitude,
                       dl_sfdc_contact.partner_contact_number__c,
                       dl_sfdc_contact.pm_certification__c,
                       dl_sfdc_contact.prior_workday_experience__c,
                       dl_sfdc_contact.qbdialer__closescore__c,
                       dl_sfdc_contact.qbdialer__contactscore__c,
                       dl_sfdc_contact.qbdialer__dials__c,
                       dl_sfdc_contact.qbdialer__responsetime__c,
                       dl_sfdc_contact.qual_score__c,
                       dl_sfdc_contact.touches_in_engagement_count__c,
                       dl_sfdc_contact.workday_years_of_experience__c,
                       dl_sfdc_contact.account_active_oppty_count__c,
                       dl_sfdc_contact.account_employee_count__c,
                       dl_sfdc_contact.account_financials_status__c,
                       dl_sfdc_contact.account_hcm_status__c,
                       dl_sfdc_contact.account_industry__c,
                       dl_sfdc_contact.account_message__c,
                       dl_sfdc_contact.account_owner__c,
                       dl_sfdc_contact.account_student_status__c,
                       dl_sfdc_contact.account_super_industry__c,
                       dl_sfdc_contact.bizible2__ad_campaign_name_ft__c,
                       dl_sfdc_contact.bizible2__ad_campaign_name_lc__c,
                       dl_sfdc_contact.bizible2__bizibleid__c,
                       dl_sfdc_contact.bizible2__landing_page_ft__c,
                       dl_sfdc_contact.bizible2__landing_page_lc__c,
                       dl_sfdc_contact.bizible2__marketing_channel_ft__c,
                       dl_sfdc_contact.bizible2__marketing_channel_lc__c,
                       dl_sfdc_contact.bizible2__touchpoint_date_ft__c,
                       dl_sfdc_contact.bizible2__touchpoint_date_lc__c,
                       dl_sfdc_contact.bizible2__touchpoint_source_ft__c,
                       dl_sfdc_contact.bizible2__touchpoint_source_lc__c,
                       dl_sfdc_contact.campaign__c,
                       dl_sfdc_contact.csd_prospecting__c,
                       dl_sfdc_contact.current_sequence_name__c,
                       dl_sfdc_contact.external_notes__c,
                       dl_sfdc_contact.key_contacts__c,
                       dl_sfdc_contact.mailingaddress,
                       dl_sfdc_contact.name_of_currently_active_sequence__c,
                       dl_sfdc_contact.nsc_training_verified__c,
                       dl_sfdc_contact.otheraddress,
                       dl_sfdc_contact.outreach_id__c,
                       dl_sfdc_contact.pl_customer_score__c,
                       dl_sfdc_contact.pl_prospect_score__c,
                       dl_sfdc_contact.primary_partner_technical_contact__c,
                       dl_sfdc_contact.primary_training_coordinator__c,
                       dl_sfdc_contact.sales_play_campaign_name__c,
                       dl_sfdc_contact.secondary_language__c,
                       dl_sfdc_contact.skip_for_self_profile_update__c,
                       dl_sfdc_contact.wallet__c,
                       dl_sfdc_contact.leandata__ld_segment__c,
                       dl_sfdc_contact.leandata__matched_buyer_persona__c,
                       dl_sfdc_contact.leandata__modified_score__c,
                       dl_sfdc_contact.leandata__routing_action__c,
                       dl_sfdc_contact.leandata__tag__c,
                       dl_sfdc_contact.marketo_person_id__c,
                       dl_sfdc_contact.last_qualified_campaign__c,
                       dl_sfdc_contact.engagement_product__c,
                       dl_sfdc_contact.blacklisted__c,
                       dl_sfdc_contact.cs_communication_preferences__c,
                       dl_sfdc_contact.do_not_call_date__c,
                       dl_sfdc_contact.dozisf__zoominfo_company_id__c,
                       dl_sfdc_contact.dozisf__zoominfo_first_updated__c,
                       dl_sfdc_contact.dozisf__zoominfo_id__c,
                       dl_sfdc_contact.dozisf__zoominfo_last_updated__c,
                       dl_sfdc_contact.email_invalid__c,
                       dl_sfdc_contact.email_opt_in__c,
                       dl_sfdc_contact.email_opt_in_date__c,
                       dl_sfdc_contact.email_opt_out_date__c,
                       dl_sfdc_contact.email_verification_confidence_level__c,
                       dl_sfdc_contact.email_verification_details__c,
                       dl_sfdc_contact.external_id__c,
                       dl_sfdc_contact.first_response_date__c,
                       dl_sfdc_contact.industry_or_line_of_business__c,
                       dl_sfdc_contact.integrate_asset_code__c,
                       dl_sfdc_contact.integrate_asset_name__c,
                       dl_sfdc_contact.leandata_routing__c,
                       dl_sfdc_contact.marketing_notes_ringlead__c,
                       dl_sfdc_contact.marketing_suspended__c,
                       dl_sfdc_contact.mql_follow_up_date__c,
                       dl_sfdc_contact.ringlead_dms_status__c,
                       dl_sfdc_contact.secondary_functional_area__c,
                       dl_sfdc_contact.sfdc_campaign_id__c,
                       dl_sfdc_contact.zoominfo_action__c,
                       dl_sfdc_contact.zoominfo_no_longer_with_company__c,
                       dl_sfdc_contact.outreach_tag__c,
                       dl_sfdc_contact.Zoominfo_Contact_Source__c,
                       row_number() OVER (PARTITION BY dl_sfdc_contact.id ORDER BY dl_sfdc_contact.etl_updated_date DESC) AS rw_nbr
                FROM data_lake.dl_sfdc_contact) derived_table1
          WHERE derived_table1.rw_nbr = 1
          UNION
          SELECT Id AS Lead_Contact_ID,
                 convertedcontactid AS Contact_id,
                 Id AS Lead_id,
                 COALESCE(convertedaccountid,account_id__c,matched_account_id__c) AS Account_id,
                 name AS Name,
                 street AS Street,
                 city AS City,
                 state AS State,
                 postalcode AS PostalCode,
                 country AS Country,
                 statecode AS State_Code,
                 countrycode AS Country_Code,
                 phone AS phone,
                 mobilephone AS mobilephone,
                 email AS email,
                 title AS Title,
                 leadsource AS LeadSource,
                 createddate AS createddate,
                 lastmodifieddate AS lastmodifieddate,
                 lastactivitydate AS lastactivitydate,
                 no_longer_w_company__c AS no_longer_w_company__c,
                 functional_role__c AS functional_role__c,
                 job_level__c AS job_level__c,
                 marketingcloudid__c AS marketingcloudid__c,
                 engagement_status__c AS engagement_status__c,
                 engagement_product__c AS engagement_product__c,
                 marketing_suspended__c AS marketing_suspended__c,
                 current_sequence_name__c AS current_sequence_name__c,
                 name_of_currently_active_sequence__c AS name_of_currently_active_sequence__c,
                 marketo_person_id__c AS marketo_person_id__c,
                 isconverted AS isconverted,
                 converteddate AS converteddate,
                 lead_domain__c AS valid_domain,
                 last_qualified_campaign__c AS last_qualified_campaign__c,
                 Reject_Recycle_Reason__c AS Reject_Reason,
                 createddate AS LeadCreateddate,
                 Email_Opt_In__c,
                 NULL AS Is_Exec_Sponsor_Contact__c,
                 NULL AS Is_Named_Supp__c,
                 ownerid AS OWNER,
                 CSD_Prospecting__c,
                 HasOptedOutOfEmail,
                 Last_MQL__c,
                 isdeleted,
                 NULL AS Zoominfo_Contact_Source__c
          FROM (SELECT dl_sfdc_lead.id,
                       dl_sfdc_lead.isdeleted,
                       dl_sfdc_lead.masterrecordid,
                       dl_sfdc_lead.lastname,
                       dl_sfdc_lead.firstname,
                       dl_sfdc_lead.salutation,
                       dl_sfdc_lead.name,
                       dl_sfdc_lead.title,
                       dl_sfdc_lead.company,
                       dl_sfdc_lead.street,
                       dl_sfdc_lead.city,
                       dl_sfdc_lead.state,
                       dl_sfdc_lead.postalcode,
                       dl_sfdc_lead.country,
                       dl_sfdc_lead.statecode,
                       dl_sfdc_lead.countrycode,
                       dl_sfdc_lead.latitude,
                       dl_sfdc_lead.longitude,
                       dl_sfdc_lead.geocodeaccuracy,
                       dl_sfdc_lead.phone,
                       dl_sfdc_lead.mobilephone,
                       dl_sfdc_lead.fax,
                       dl_sfdc_lead.email,
                       dl_sfdc_lead.website,
                       dl_sfdc_lead.photourl,
                       dl_sfdc_lead.description,
                       dl_sfdc_lead.leadsource,
                       dl_sfdc_lead.status,
                       dl_sfdc_lead.industry,
                       dl_sfdc_lead.rating,
                       dl_sfdc_lead.currencyisocode,
                       dl_sfdc_lead.annualrevenue,
                       dl_sfdc_lead.numberofemployees,
                       dl_sfdc_lead.ownerid,
                       dl_sfdc_lead.hasoptedoutofemail,
                       dl_sfdc_lead.isconverted,
                       dl_sfdc_lead.converteddate,
                       dl_sfdc_lead.convertedaccountid,
                       dl_sfdc_lead.convertedcontactid,
                       dl_sfdc_lead.convertedopportunityid,
                       dl_sfdc_lead.isunreadbyowner,
                       dl_sfdc_lead.createddate,
                       dl_sfdc_lead.createdbyid,
                       dl_sfdc_lead.lastmodifieddate,
                       dl_sfdc_lead.lastmodifiedbyid,
                       dl_sfdc_lead.systemmodstamp,
                       dl_sfdc_lead.lastactivitydate,
                       dl_sfdc_lead.donotcall,
                       dl_sfdc_lead.hasoptedoutoffax,
                       dl_sfdc_lead.lastvieweddate,
                       dl_sfdc_lead.lastreferenceddate,
                       dl_sfdc_lead.lasttransferdate,
                       dl_sfdc_lead.partneraccountid,
                       dl_sfdc_lead.jigsaw,
                       dl_sfdc_lead.jigsawcontactid,
                       dl_sfdc_lead.cleanstatus,
                       dl_sfdc_lead.companydunsnumber,
                       dl_sfdc_lead.dandbcompanyid,
                       dl_sfdc_lead.emailbouncedreason,
                       dl_sfdc_lead.emailbounceddate,
                       dl_sfdc_lead.hcm_systems_of_record__c,
                       dl_sfdc_lead.financials_logistics_systems_of_record2__c,
                       dl_sfdc_lead.hcm_products__c,
                       dl_sfdc_lead.project_timeline__c,
                       dl_sfdc_lead.existing_rdbms__c,
                       dl_sfdc_lead.comments_handling_instructions__c,
                       dl_sfdc_lead.preferred_communication__c,
                       dl_sfdc_lead.financials_products__c,
                       dl_sfdc_lead.payroll_providers__c,
                       dl_sfdc_lead.referral_source__c,
                       dl_sfdc_lead.existing_environment__c,
                       dl_sfdc_lead.marketing_touch_points__c,
                       dl_sfdc_lead.marketing_activity__c,
                       dl_sfdc_lead.project_drivers__c,
                       dl_sfdc_lead.employee_range__c,
                       dl_sfdc_lead.revenue_range__c,
                       dl_sfdc_lead.workday_country__c,
                       dl_sfdc_lead.resource_management_products__c,
                       dl_sfdc_lead.project_funded__c,
                       dl_sfdc_lead.reject_reason__c,
                       dl_sfdc_lead.engagement_type__c,
                       dl_sfdc_lead.lead_profile__c,
                       dl_sfdc_lead.revenue_management_products__c,
                       dl_sfdc_lead.next_steps__c,
                       dl_sfdc_lead.newsletter__c,
                       dl_sfdc_lead.upgrade__c,
                       dl_sfdc_lead.relationship_to_workday__c,
                       dl_sfdc_lead.hr_webinar_11_14_06__c,
                       dl_sfdc_lead.it_webinar_11_16_06__c,
                       dl_sfdc_lead.you_would_describe_your_company_as__c,
                       dl_sfdc_lead.partner_provides__c,
                       dl_sfdc_lead.partner_interest__c,
                       dl_sfdc_lead.registered_through__c,
                       dl_sfdc_lead.other_phone__c,
                       dl_sfdc_lead.integration__c,
                       dl_sfdc_lead.functional_role__c,
                       dl_sfdc_lead.referred_from__c,
                       dl_sfdc_lead.hr_niche_system__c,
                       dl_sfdc_lead.rejection_segment__c,
                       dl_sfdc_lead.support__c,
                       dl_sfdc_lead.event_location__c,
                       dl_sfdc_lead.product_interest__c,
                       dl_sfdc_lead.referral_specifics__c,
                       dl_sfdc_lead.average_customer_size_employ_rev__c,
                       dl_sfdc_lead.contingent_workers__c,
                       dl_sfdc_lead.number_of_years_in_business__c,
                       dl_sfdc_lead.global_company__c,
                       dl_sfdc_lead.of_new_revenue__c,
                       dl_sfdc_lead.current_customer_size__c,
                       dl_sfdc_lead.oskeyid__c,
                       dl_sfdc_lead.product_preview_demos__c,
                       dl_sfdc_lead.do_you_have_workday_customers__c,
                       dl_sfdc_lead.of_offices__c,
                       dl_sfdc_lead.headquaters__c,
                       dl_sfdc_lead.hq_location__c,
                       dl_sfdc_lead.erp_experience__c,
                       dl_sfdc_lead.sic_code__c,
                       dl_sfdc_lead.who_do_you_compete_with__c,
                       dl_sfdc_lead.how_do_you_differentiate_from_others__c,
                       dl_sfdc_lead.name_of_workday_sponsor__c,
                       dl_sfdc_lead.customers_that_requesting_workday__c,
                       dl_sfdc_lead.target_market__c,
                       dl_sfdc_lead.currently_partner_with_other_hcm_vendors__c,
                       dl_sfdc_lead.duns_number__c,
                       dl_sfdc_lead.sic_description__c,
                       dl_sfdc_lead.job_level__c,
                       dl_sfdc_lead.validation__c,
                       dl_sfdc_lead.validation_date__c,
                       dl_sfdc_lead.roi_analysis_link__c,
                       dl_sfdc_lead.program_name__c,
                       dl_sfdc_lead.trade_show_notes__c,
                       dl_sfdc_lead.tempcountry__c,
                       dl_sfdc_lead.converted_from_lead__c,
                       dl_sfdc_lead.purge_or_archive__c,
                       dl_sfdc_lead.lead_number__c,
                       dl_sfdc_lead.round_robin_id__c,
                       dl_sfdc_lead.tempstate__c,
                       dl_sfdc_lead.consent_last_updated__c,
                       dl_sfdc_lead.token__c,
                       dl_sfdc_lead.newsletters_blogs__c,
                       dl_sfdc_lead.events__c,
                       dl_sfdc_lead.product_information_announcements__c,
                       dl_sfdc_lead.consent_type__c,
                       dl_sfdc_lead.consent_source__c,
                       dl_sfdc_lead.area_code__c,
                       dl_sfdc_lead.area_code_format_1__c,
                       dl_sfdc_lead.area_code_format_2__c,
                       dl_sfdc_lead.country_format_1__c,
                       dl_sfdc_lead.area_code_calc__c,
                       dl_sfdc_lead.assignment_rule_change_del__c,
                       dl_sfdc_lead.lead_update_del__c,
                       dl_sfdc_lead.fortune_1_000__c,
                       dl_sfdc_lead.upgrade_replace__c,
                       dl_sfdc_lead.qual_score__c,
                       dl_sfdc_lead.int_score__c,
                       dl_sfdc_lead.ls_lead_rating__c,
                       dl_sfdc_lead.financials_response__c,
                       dl_sfdc_lead.server_path__c,
                       dl_sfdc_lead.lead_rating_image__c,
                       dl_sfdc_lead.qualification_meter__c,
                       dl_sfdc_lead.interest_meter__c,
                       dl_sfdc_lead.hcm_system_of_record__c,
                       dl_sfdc_lead.financials_logistics_systems_of_record__c,
                       dl_sfdc_lead.ls_completion__c,
                       dl_sfdc_lead.profile_completeness_meter__c,
                       dl_sfdc_lead.profile_status__c,
                       dl_sfdc_lead.unsync_with_mkto__c,
                       dl_sfdc_lead.sflma__subscriber_org_type__c,
                       dl_sfdc_lead.csd_flag__c,
                       dl_sfdc_lead.matched_account_type__c,
                       dl_sfdc_lead.custom_convert__c,
                       dl_sfdc_lead.matched_contact_id__c,
                       dl_sfdc_lead.matched_by_code__c,
                       dl_sfdc_lead.marketingcloudid__c,
                       dl_sfdc_lead.account_name_local_language__c,
                       dl_sfdc_lead.address_local_language__c,
                       dl_sfdc_lead.name_local_language__c,
                       dl_sfdc_lead.lid__linkedin_company_id__c,
                       dl_sfdc_lead.lid__linkedin_member_token__c,
                       dl_sfdc_lead.title_local_language__c,
                       dl_sfdc_lead.jsimpacts__added_from_data_com__c,
                       dl_sfdc_lead.jsimpacts__data_com_do_not_auto_update__c,
                       dl_sfdc_lead.jsimpacts__data_com_managed__c,
                       dl_sfdc_lead.jsimpacts__imported_from_jigsaw__c,
                       dl_sfdc_lead.marketo_phone__c,
                       dl_sfdc_lead.demand_funnel_stage__c,
                       dl_sfdc_lead.lead_count__c,
                       dl_sfdc_lead.is_converted_lead__c,
                       dl_sfdc_lead.send_reject_notification__c,
                       dl_sfdc_lead.year_founded__c,
                       dl_sfdc_lead.complimentary_workday_solution__c,
                       dl_sfdc_lead.privacy_policy_agreement__c,
                       dl_sfdc_lead.customer_base_response__c,
                       dl_sfdc_lead.e_g_exec_change__c,
                       dl_sfdc_lead.expansion_growth__c,
                       dl_sfdc_lead.fins_exec_change__c,
                       dl_sfdc_lead.hr_exec_change__c,
                       dl_sfdc_lead.ipo_or_funding_growth__c,
                       dl_sfdc_lead.it_exec_change__c,
                       dl_sfdc_lead.lattice_attach_score__c,
                       dl_sfdc_lead.contact_intelligence_dashboard__c,
                       dl_sfdc_lead.survey_responses__c,
                       dl_sfdc_lead.time_attendance_system_of_record__c,
                       dl_sfdc_lead.demand_base_id__c,
                       dl_sfdc_lead.forbes_2000__c,
                       dl_sfdc_lead.keep_informed_about_workday__c,
                       dl_sfdc_lead.main_concerns_with_current_hr_system__c,
                       dl_sfdc_lead.plans_for_hr_system__c,
                       dl_sfdc_lead.plans_for_current_financial_system__c,
                       dl_sfdc_lead.plans_for_your_current_system__c,
                       dl_sfdc_lead.lattice_financials_score__c,
                       dl_sfdc_lead.lattice_hcm_score__c,
                       dl_sfdc_lead.m_a_divest_growth__c,
                       dl_sfdc_lead.ops_exec_change__c,
                       dl_sfdc_lead.positive_financial_performance__c,
                       dl_sfdc_lead.rising_14_functional_role__c,
                       dl_sfdc_lead.rising_14_industry__c,
                       dl_sfdc_lead.rising_14_job_title__c,
                       dl_sfdc_lead.rising_14_job_level__c,
                       dl_sfdc_lead.rising_14_what_workday_applications_s__c,
                       dl_sfdc_lead.rising_14_how_many_years_of_experience__c,
                       dl_sfdc_lead.venturemessage__c,
                       dl_sfdc_lead.qbdialer__closedate__c,
                       dl_sfdc_lead.lattice_account_id__c,
                       dl_sfdc_lead.marketo_job_title__c,
                       dl_sfdc_lead.qbdialer__closescore__c,
                       dl_sfdc_lead.qbdialer__contactdate__c,
                       dl_sfdc_lead.qbdialer__contactscoreid__c,
                       dl_sfdc_lead.qbdialer__contactscore__c,
                       dl_sfdc_lead.qbdialer__dials__c,
                       dl_sfdc_lead.qbdialer__lastcalltime__c,
                       dl_sfdc_lead.qbdialer__responsetime__c,
                       dl_sfdc_lead.lead_domain__c,
                       dl_sfdc_lead.qbdialer__timezonesidkey__c,
                       dl_sfdc_lead.lead_id_case_safe__c,
                       dl_sfdc_lead.matched_account_id__c,
                       dl_sfdc_lead.integrate_publisher_id__c,
                       dl_sfdc_lead.department__c,
                       dl_sfdc_lead.department_local_language__c,
                       dl_sfdc_lead.first_csd_ae_connect__c,
                       dl_sfdc_lead.first_csd_connect__c,
                       dl_sfdc_lead.first_csd_reachout__c,
                       dl_sfdc_lead.first_mql__c,
                       dl_sfdc_lead.first_marketing_response__c,
                       dl_sfdc_lead.last_csd_ae_connect__c,
                       dl_sfdc_lead.last_csd_connect__c,
                       dl_sfdc_lead.last_csd_reachout__c,
                       dl_sfdc_lead.last_mql__c,
                       dl_sfdc_lead.last_marketing_response__c,
                       dl_sfdc_lead.touches_in_engagement_count__c,
                       dl_sfdc_lead.marketing_response_count__c,
                       dl_sfdc_lead.marketing_opt_out__c,
                       dl_sfdc_lead.mkto_si__add_to_marketo_campaign__c,
                       dl_sfdc_lead.mkto_si__hidedate__c,
                       dl_sfdc_lead.mkto_si__last_interesting_moment_date__c,
                       dl_sfdc_lead.mkto_si__last_interesting_moment_desc__c,
                       dl_sfdc_lead.mkto_si__last_interesting_moment_source__c,
                       dl_sfdc_lead.mkto_si__last_interesting_moment_type__c,
                       dl_sfdc_lead.mkto_si__last_interesting_moment__c,
                       dl_sfdc_lead.mkto_si__msicontactid__c,
                       dl_sfdc_lead.mkto_si__priority__c,
                       dl_sfdc_lead.mkto_si__relative_score_value__c,
                       dl_sfdc_lead.mkto_si__relative_score__c,
                       dl_sfdc_lead.mkto_si__urgency_value__c,
                       dl_sfdc_lead.mkto_si__urgency__c,
                       dl_sfdc_lead.mkto_si__view_in_marketo__c,
                       dl_sfdc_lead.account_id__c,
                       dl_sfdc_lead.annual_revenue_range__c,
                       dl_sfdc_lead.contact_request__c,
                       dl_sfdc_lead.marketing_notes__c,
                       dl_sfdc_lead.engagement_status__c,
                       dl_sfdc_lead.last_email_sales__c,
                       dl_sfdc_lead.last_email_csd__c,
                       dl_sfdc_lead.reject_recycle_reason__c,
                       dl_sfdc_lead.engagement_status_priority__c,
                       dl_sfdc_lead.matched_account_opps__c,
                       dl_sfdc_lead.start_date_of_current_engagement_stage__c,
                       dl_sfdc_lead.last_csd_reachout_task__c,
                       dl_sfdc_lead.sla_status__c,
                       dl_sfdc_lead.engagement_stage_end_date__c,
                       dl_sfdc_lead.engagement_stage_days_remaining__c,
                       dl_sfdc_lead.prior_engagement_stage__c,
                       dl_sfdc_lead.update_lead__c,
                       dl_sfdc_lead.copy_of_email_adress__c,
                       dl_sfdc_lead.pre_trigger_account_match__c,
                       dl_sfdc_lead.pre_trigger_engagement_stage__c,
                       dl_sfdc_lead.accountcsid__c,
                       dl_sfdc_lead.reject_sub_reason__c,
                       dl_sfdc_lead.reject_reason_detail__c,
                       dl_sfdc_lead.etl_created_date,
                       dl_sfdc_lead.etl_created_by,
                       dl_sfdc_lead.etl_updated_date,
                       dl_sfdc_lead.etl_updated_by,
                       dl_sfdc_lead.account_active_oppty_count__c,
                       dl_sfdc_lead.account_employee_count__c,
                       dl_sfdc_lead.account_financials_status__c,
                       dl_sfdc_lead.account_hcm_status__c,
                       dl_sfdc_lead.account_industry__c,
                       dl_sfdc_lead.account_name__c,
                       dl_sfdc_lead.account_owner__c,
                       dl_sfdc_lead.account_student_status__c,
                       dl_sfdc_lead.account_super_industry__c,
                       dl_sfdc_lead.address,
                       dl_sfdc_lead.bizible2__account__c,
                       dl_sfdc_lead.bizible2__ad_campaign_name_ft__c,
                       dl_sfdc_lead.bizible2__ad_campaign_name_lc__c,
                       dl_sfdc_lead.bizible2__bizibleid__c,
                       dl_sfdc_lead.bizible2__landing_page_ft__c,
                       dl_sfdc_lead.bizible2__landing_page_lc__c,
                       dl_sfdc_lead.bizible2__marketing_channel_ft__c,
                       dl_sfdc_lead.bizible2__marketing_channel_lc__c,
                       dl_sfdc_lead.bizible2__touchpoint_date_ft__c,
                       dl_sfdc_lead.bizible2__touchpoint_date_lc__c,
                       dl_sfdc_lead.bizible2__touchpoint_source_ft__c,
                       dl_sfdc_lead.bizible2__touchpoint_source_lc__c,
                       dl_sfdc_lead.csd_prospecting__c,
                       dl_sfdc_lead.current_sequence_name__c,
                       dl_sfdc_lead.name_of_currently_active_sequence__c,
                       dl_sfdc_lead.outreach_id__c,
                       dl_sfdc_lead.pl_customer_score__c,
                       dl_sfdc_lead.pl_prospect_score__c,
                       dl_sfdc_lead.leandata__a2b_account__c,
                       dl_sfdc_lead.leandata__a2b_group__c,
                       dl_sfdc_lead.leandata__ld_segment__c,
                       dl_sfdc_lead.leandata__marketing_sys_created_date__c,
                       dl_sfdc_lead.leandata__matched_account__c,
                       dl_sfdc_lead.leandata__matched_buyer_persona__c,
                       dl_sfdc_lead.leandata__matched_lead__c,
                       dl_sfdc_lead.leandata__modified_score__c,
                       dl_sfdc_lead.leandata__reporting_matched_account__c,
                       dl_sfdc_lead.leandata__reporting_timestamp__c,
                       dl_sfdc_lead.leandata__router_status__c,
                       dl_sfdc_lead.leandata__routing_action__c,
                       dl_sfdc_lead.leandata__routing_status__c,
                       dl_sfdc_lead.leandata__search__c,
                       dl_sfdc_lead.leandata__search_index__c,
                       dl_sfdc_lead.leandata__status_info__c,
                       dl_sfdc_lead.leandata__tag__c,
                       dl_sfdc_lead.marketo_person_id__c,
                       dl_sfdc_lead.last_qualified_campaign__c,
                       dl_sfdc_lead.engagement_product__c,
                       dl_sfdc_lead.blacklisted__c,
                       dl_sfdc_lead.bombora_app__bombora_last_date_time_updated__c,
                       dl_sfdc_lead.bombora_app__bombora_surge_record_count__c,
                       dl_sfdc_lead.bombora_app__bombora_total_composite_score__c,
                       dl_sfdc_lead.do_not_call_date__c,
                       dl_sfdc_lead.dozisf__zoominfo_company_id__c,
                       dl_sfdc_lead.dozisf__zoominfo_first_updated__c,
                       dl_sfdc_lead.dozisf__zoominfo_id__c,
                       dl_sfdc_lead.dozisf__zoominfo_last_updated__c,
                       dl_sfdc_lead.email_invalid__c,
                       dl_sfdc_lead.email_opt_in__c,
                       dl_sfdc_lead.email_opt_in_date__c,
                       dl_sfdc_lead.email_opt_out_date__c,
                       dl_sfdc_lead.email_verification_confidence_level__c,
                       dl_sfdc_lead.email_verification_details__c,
                       dl_sfdc_lead.external_id__c,
                       dl_sfdc_lead.fins_wam__c,
                       dl_sfdc_lead.first_response_date__c,
                       dl_sfdc_lead.hcm_wam__c,
                       dl_sfdc_lead.integrate_asset_code__c,
                       dl_sfdc_lead.integrate_asset_name__c,
                       dl_sfdc_lead.leandata_routing__c,
                       dl_sfdc_lead.marketing_notes_ringlead__c,
                       dl_sfdc_lead.marketing_suspended__c,
                       dl_sfdc_lead.matched_account_active_opportunity_count__c,
                       dl_sfdc_lead.matched_account_additional_ae__c,
                       dl_sfdc_lead.matched_account_annual_revenue__c,
                       dl_sfdc_lead.matched_account_classification__c,
                       dl_sfdc_lead.matched_account_classification_range__c,
                       dl_sfdc_lead.matched_account_csd_prospecting__c,
                       dl_sfdc_lead.matched_account_cust_satisfaction_ind__c,
                       dl_sfdc_lead.matched_account_customer_base_ae__c,
                       dl_sfdc_lead.matched_account_customer_of__c,
                       dl_sfdc_lead.matched_account_deploy_total_tenant_cnt__c,
                       dl_sfdc_lead.matched_account_employees__c,
                       dl_sfdc_lead.matched_account_fin_systems_of_record__c,
                       dl_sfdc_lead.matched_account_financials_lead__c,
                       dl_sfdc_lead.matched_account_financials_status__c,
                       dl_sfdc_lead.matched_account_fins_wam__c,
                       dl_sfdc_lead.matched_account_forbes_2000__c,
                       dl_sfdc_lead.matched_account_group__c,
                       dl_sfdc_lead.matched_account_hcm_status__c,
                       dl_sfdc_lead.matched_account_hcm_wam__c,
                       dl_sfdc_lead.matched_account_hr_systems_of_record__c,
                       dl_sfdc_lead.matched_account_industry__c,
                       dl_sfdc_lead.matched_account_init_deployment_approach__c,
                       dl_sfdc_lead.matched_account_name__c,
                       dl_sfdc_lead.matched_account_new_implementing_cust__c,
                       dl_sfdc_lead.matched_account_not_renewing__c,
                       dl_sfdc_lead.matched_account_oppty_count_sourcing__c,
                       dl_sfdc_lead.matched_account_oppty_count_workday__c,
                       dl_sfdc_lead.matched_account_owner__c,
                       dl_sfdc_lead.matched_account_pbu_engagement_level__c,
                       dl_sfdc_lead.matched_account_pbu_name__c,
                       dl_sfdc_lead.matched_account_pbu_status__c,
                       dl_sfdc_lead.matched_account_pbu_type__c,
                       dl_sfdc_lead.matched_account_planning_lead__c,
                       dl_sfdc_lead.matched_account_product_deployed_fin__c,
                       dl_sfdc_lead.matched_account_product_deployed_hcm__c,
                       dl_sfdc_lead.matched_account_product_deployed_payro__c,
                       dl_sfdc_lead.matched_account_region__c,
                       dl_sfdc_lead.matched_account_segment__c,
                       dl_sfdc_lead.matched_account_status__c,
                       dl_sfdc_lead.matched_account_student_admin_systems__c,
                       dl_sfdc_lead.matched_account_student_status__c,
                       dl_sfdc_lead.matched_account_super_industry__c,
                       dl_sfdc_lead.matched_account_suspend_marketing_emails__c,
                       dl_sfdc_lead.matched_account_total_products_deployed__c,
                       dl_sfdc_lead.matched_account_type_ld__c,
                       dl_sfdc_lead.most_recent_sales_connect__c,
                       dl_sfdc_lead.most_recent_sales_reach_out__c,
                       dl_sfdc_lead.mql_follow_up_date__c,
                       dl_sfdc_lead.no_longer_w_company__c,
                       dl_sfdc_lead.ringlead_dms_status__c,
                       dl_sfdc_lead.sfdc_campaign_id__c,
                       dl_sfdc_lead.zoominfo_no_longer_with_company__c,
                       dl_sfdc_lead.outreach_tag__c,
                       row_number() OVER (PARTITION BY dl_sfdc_lead.id ORDER BY dl_sfdc_lead.etl_updated_date DESC) AS rw_nbr
                FROM data_lake.dl_sfdc_lead) derived_table1
          WHERE derived_table1.rw_nbr = 1
          AND   convertedcontactid IS NULL);
    """
              )
            )
        )

        def merge_original(original):

            def internal(element):
                data = element.asDict(recursive = True)
                data['original'] = original

                return Row(**data)

            return internal

        for row in input102.rdd.toLocalIterator():
            result = []
            index = 0

            for query in row._sql_query:
                spark.sql(query)
                result += [Row(execution = str(index), sqlStatement = query, count = 0, message = "success")]
                index += 1

            tmp = spark.createDataFrame([Row(result = result)])
            tmp = tmp.rdd\
                      .map(merge_original(row))\
                      .toDF(StructType(tmp.schema.fields + [StructField("original", input102.schema, True)]))

            if output101 is None:
                output101 = tmp
            else:
                output101 = output101.union(tmp)

        if isInputEmpty:
            output101 = spark.createDataFrame([], output101.schema)

    import subprocess
    result = subprocess.run(["ls"], capture_output = True, text = True)
    # result1=subprocess.run(["pwd"], capture_output=True, text=True)
    data = [StructField(item, StringType(), True) for item in result.stdout.split("\n")]
    # data.append((result1.stdout,))
    print(data)
    deptDF = spark.createDataFrame(data = [], schema = StructType(data))
    deptDF.printSchema()
    out0 = in0.select("c  date")

    return out0
